FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY  . .

RUN CGO_ENABLED=0 GOOS=linux go build -o notification ./cmd/main.go


FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/notification .

EXPOSE 4000
CMD [ "./notification" ]

