version: '3.8'

services:

    postgres:
        image: postgres:15-alpine
        container_name: buyitnow_postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
            interval: 10s
            timeout: 5s
            retries: 5
    redis:
        image: redis:7-alpine
        container_name: buyitnow_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: buyitnow_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s

    # Ecommerce app

    buyitnow:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: buyitnow_app
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        restart: on-failure

    #Notification

    notification:
        build:
            context: ./notification-service
            dockerfile: Dockerfile
        container_name: buyitnow_notification
        env_file:
            - ./notification-service/.env
        depends_on:
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: on-failure

volumes:
    postgres_data:
    redis_data:
    rabbitmq_data:

