// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sangeeth518/go-Ecommerce/pkg/api"
	"github.com/sangeeth518/go-Ecommerce/pkg/api/handler"
	"github.com/sangeeth518/go-Ecommerce/pkg/config"
	"github.com/sangeeth518/go-Ecommerce/pkg/db"
	"github.com/sangeeth518/go-Ecommerce/pkg/helper"
	"github.com/sangeeth518/go-Ecommerce/pkg/repository"
	"github.com/sangeeth518/go-Ecommerce/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHttp, error) {
	gormDB, err := db.ConnectDB(cfg)
	if err != nil {
		return nil, err
	}
	redisClient, err := db.ConnectRedis(cfg)
	if err != nil {
		return nil, err
	}
	redisCache := db.NewRedisCache(redisClient)
	adminRepo := repository.NewAdminRepository(gormDB)
	interfacesHelper, err := helper.NewHelper(cfg)
	if err != nil {
		return nil, err
	}
	adminUseCase := usecase.NewAdminUsecase(adminRepo, interfacesHelper)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	userRepo := repository.NewUserRepository(gormDB)
	userUsecase := usecase.NewUserUsecase(userRepo, interfacesHelper)
	userHandler := handler.NewUserHandler(userUsecase)
	categoryRepo := repository.NewCategoryRepository(gormDB)
	cateoryUsecase := usecase.NewCategoryUsecase(categoryRepo, interfacesHelper)
	categoryHandler := handler.NewCategoryHandler(cateoryUsecase)
	inventoryRepo := repository.NewInventoryRepository(gormDB)
	inventoryUsecase := usecase.NewInventoryUsecase(inventoryRepo, interfacesHelper, redisCache)
	inventoryHandler := handler.NewInventoryHandler(inventoryUsecase)
	cartRepository := repository.NewCartRepository(gormDB)
	cartUsecase := usecase.NewCartUsecase(cartRepository)
	cartHandler := handler.NewCartHandler(cartUsecase)
	orderRepo := repository.NewOrderRepo(gormDB)
	orderUsecase := usecase.NewOrderUsecase(orderRepo, interfacesHelper)
	orderHandler := handler.NewOrderHandler(orderUsecase)
	serverHttp := http.NewServerHttp(adminHandler, userHandler, categoryHandler, inventoryHandler, cartHandler, orderHandler, cfg)
	return serverHttp, nil
}
