// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/helper/interface/helper.go

// Package mockhelper is a generated GoMock package.
package mockhelper

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sangeeth518/go-Ecommerce/pkg/utils/models"
)

// MockHelper is a mock of Helper interface.
type MockHelper struct {
	ctrl     *gomock.Controller
	recorder *MockHelperMockRecorder
}

// MockHelperMockRecorder is the mock recorder for MockHelper.
type MockHelperMockRecorder struct {
	mock *MockHelper
}

// NewMockHelper creates a new mock instance.
func NewMockHelper(ctrl *gomock.Controller) *MockHelper {
	mock := &MockHelper{ctrl: ctrl}
	mock.recorder = &MockHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelper) EXPECT() *MockHelperMockRecorder {
	return m.recorder
}

// AddProductImage mocks base method.
func (m *MockHelper) AddProductImage(ctx context.Context, file *multipart.FileHeader, productId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProductImage", ctx, file, productId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProductImage indicates an expected call of AddProductImage.
func (mr *MockHelperMockRecorder) AddProductImage(ctx, file, productId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductImage", reflect.TypeOf((*MockHelper)(nil).AddProductImage), ctx, file, productId)
}

// CompareHashPassword mocks base method.
func (m *MockHelper) CompareHashPassword(password, givenpass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHashPassword", password, givenpass)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompareHashPassword indicates an expected call of CompareHashPassword.
func (mr *MockHelperMockRecorder) CompareHashPassword(password, givenpass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareHashPassword", reflect.TypeOf((*MockHelper)(nil).CompareHashPassword), password, givenpass)
}

// DeleteProductImageFromS3 mocks base method.
func (m *MockHelper) DeleteProductImageFromS3(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductImageFromS3", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductImageFromS3 indicates an expected call of DeleteProductImageFromS3.
func (mr *MockHelperMockRecorder) DeleteProductImageFromS3(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductImageFromS3", reflect.TypeOf((*MockHelper)(nil).DeleteProductImageFromS3), ctx, key)
}

// GenerateInvoicePDF mocks base method.
func (m *MockHelper) GenerateInvoicePDF(details models.OrderDetailsResponse) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInvoicePDF", details)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInvoicePDF indicates an expected call of GenerateInvoicePDF.
func (mr *MockHelperMockRecorder) GenerateInvoicePDF(details interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInvoicePDF", reflect.TypeOf((*MockHelper)(nil).GenerateInvoicePDF), details)
}

// GenerateTokenAdmin mocks base method.
func (m *MockHelper) GenerateTokenAdmin(admin models.AdminDetailResponse) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenAdmin", admin)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateTokenAdmin indicates an expected call of GenerateTokenAdmin.
func (mr *MockHelperMockRecorder) GenerateTokenAdmin(admin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenAdmin", reflect.TypeOf((*MockHelper)(nil).GenerateTokenAdmin), admin)
}

// GenerateTokenClient mocks base method.
func (m *MockHelper) GenerateTokenClient(user models.UserDetailsResponse) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenClient", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenClient indicates an expected call of GenerateTokenClient.
func (mr *MockHelperMockRecorder) GenerateTokenClient(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenClient", reflect.TypeOf((*MockHelper)(nil).GenerateTokenClient), user)
}

// GetPresignedURL mocks base method.
func (m *MockHelper) GetPresignedURL(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedURL", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedURL indicates an expected call of GetPresignedURL.
func (mr *MockHelperMockRecorder) GetPresignedURL(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedURL", reflect.TypeOf((*MockHelper)(nil).GetPresignedURL), ctx, key)
}

// PasswordHashing mocks base method.
func (m *MockHelper) PasswordHashing(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordHashing", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasswordHashing indicates an expected call of PasswordHashing.
func (mr *MockHelperMockRecorder) PasswordHashing(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordHashing", reflect.TypeOf((*MockHelper)(nil).PasswordHashing), password)
}
