name: BuyItNow CI

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
          cache: true
      
      - name: Download dependencies
        run: go mod download

      - name: Verify module integrity
        run: go mod verify
      
      - name: run tests
        run: go test -v -race -cover ./...

      - name: Build 
        run: go build ./..

      

 