name: BuyItNow CI

on:
  push:
    branches: [ main, master ]

jobs:
  ecommerce:
    name: Ecommerce — Build, Vet and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
          cache: true
      
      - name: Download dependencies
        run: go mod download

      - name: Verify module integrity
        run: go mod verify
      
      - name: run tests
        run: go test -v -race -cover ./...

      - name: Build 
        run: go build ./...
  
  #Job 2 Notification servicee
  notification:
    name: Notification -- Build and Vet
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./notification-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
         go-version: "1.26"
         cache: true
      - name: download dependencies
        run: go mod download

      - name: Verify module
        run: go mod verify
      
      - name: Run tests
  run: go test -v -race -cover ./...
      
      - name: Build
        run: go build ./...

      - name: Vet 
        run: go vet ./...

      

  



  

      

 